import sys
import hashlib
import datetime
sys.path.insert(0, '/home/denkaai/KIFAA/engine1_shield')
sys.path.insert(0, '/home/denkaai/KIFAA/engine2_trace')

from shield import run_shield
from trace import run_trace

def generate_report():
    print("[KIFAA] Generating court-ready evidence report...")
    
    threats = run_shield()
    results = run_trace()
    
    now = datetime.datetime.now()
    
    report = f"""
╔══════════════════════════════════════════════════════════╗
║            KIFAA — COURT EVIDENCE REPORT                 ║
║       Kenya Intelligence Forensics & Analysis            ║
║       CASE: KIFAA/DCI/CYBER/{now.strftime('%Y%m%d')}/001            ║
║       CLASSIFICATION: RESTRICTED                         ║
╚══════════════════════════════════════════════════════════╝

REPORT GENERATED: {now.strftime('%Y-%m-%d %H:%M:%S')}
INVESTIGATOR:     Denis Munene (Denkaai)
INSTITUTION:      Thika Technical Training Institute
PLATFORM:         KIFAA v1.0

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 1: SACCO BREACH ANALYSIS (Engine 1 — SACCOShield)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Threats Detected:  {len(threats)}
Critical Threats:        {len([t for t in threats if t['severity']=='CRITICAL'])}
High Threats:            {len([t for t in threats if t['severity']=='HIGH'])}
Medium Threats:          {len([t for t in threats if t['severity']=='MEDIUM'])}

THREAT DETAILS:
"""
    for t in threats[:5]:
        report += f"""
  Type:      {t['type']}
  Severity:  {t['severity']}
  Time:      {t['timestamp']}
  User:      {t['user']}
  IP:        {t['ip']}
  Detail:    {t['detail']}
  ─────────────────────────────────
"""

    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 2: M-PESA FRAUD ANALYSIS (Engine 2 — KenyaTrace)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Fraud Transactions: {results['fraud_count']}
Total Amount Stolen:      KES {results['total_fraud']:,}
Money Mule Accounts:      {len(results['mules'])}
Master Account:           {results['master']}
Network Nodes Mapped:     {results['graph_nodes']}

MONEY MULE ACCOUNTS:
"""
    for m in results['mules']:
        report += f"  Phone: {m['phone']} | Transfers: {m['count']} | Total: KES {m['total']:,}\n"

    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 3: LEGAL FRAMEWORK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Applicable Laws:
  1. Computer Misuse & Cybercrimes Act 2018 — Section 4
     Unauthorized access to computer systems
  2. Computer Misuse & Cybercrimes Act 2018 — Section 27
     Phishing and fraud
  3. Computer Misuse & Cybercrimes Act 2018 — Section 26
     Identity theft
  4. Penal Code Cap 63 — Section 275
     Obtaining by false pretenses
  5. Proceeds of Crime & Anti-Money Laundering Act 2009
     Money laundering via M-PESA mule network

Court Orders Required:
  1. Safaricom — Subscriber details for mule accounts
  2. Faiba Kenya — Subscriber details for hacker IP
  3. Search warrant for suspect premises

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 4: EVIDENCE INTEGRITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    # Hash the report for integrity
    report_hash = hashlib.sha256(report.encode()).hexdigest()
    report += f"""
Report SHA256:    {report_hash}
Generated by:     KIFAA v1.0
Timestamp:        {now.strftime('%Y-%m-%d %H:%M:%S')}

This report was generated automatically by KIFAA.
Evidence has been preserved with SHA256 hash verification
for court admissibility under Kenya Evidence Act Cap 80.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
END OF KIFAA COURT EVIDENCE REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    # Save report
    with open('/home/denkaai/KIFAA/reports/KIFAA_CASE_REPORT.txt','w') as f:
        f.write(report)

    # Hash the saved file
    with open('/home/denkaai/KIFAA/reports/KIFAA_CASE_REPORT.txt','rb') as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()

    print("[✓] Court report generated!")
    print(f"[✓] Report saved: reports/KIFAA_CASE_REPORT.txt")
    print(f"[✓] SHA256: {file_hash}")
    print("[✓] Evidence integrity verified!")

if __name__ == "__main__":
    generate_report()
